name: Terraform

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Debug ENV
        run: |
          if [ -z "$TF_API_TOKEN" ]; then
            echo "❌ TF_API_TOKEN not set"
            exit 1
          else
            echo "✅ TF_API_TOKEN is set (value hidden)"
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

