
name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5   # pick your version

      - name: Configure Terraform Cloud token
        env:
          # Map GitHub secret to what Terraform expects
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
        run: |
          echo "Terraform Cloud token configured"
          if [ -z "$TF_TOKEN_app_terraform_io" ]; then
            echo "❌ Token not found!"
            exit 1
          fi

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false

